import Head from "next/head";
import Image from "next/image";
import "antd/dist/antd.css"; // or 'antd/dist/antd.less'
import { Layout, Menu, Row, Col, Carousel } from "antd";
import styles from "../styles/Home.module.css";
import { Card, Avatar } from "antd";
import { useQuery } from "graphql-hooks";
const { Header, Footer, Sider, Content } = Layout;
import Img1 from "../public/Images/img-1.webp";
import Img2 from "../public/Images/img-2.jpg";
import Img3 from "../public/Images/img-3.jpg";
import Img4 from "../public/Images/img-4.jpg";
import Link from "next/link";
import { useEffect } from "react";
import  Pageheader  from "../pages/Components/index.jsx";
const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;
const { Meta } = Card;
const contentStyle = {
  width: "100%",
  height: "auto",
  color: "#fff",
  lineHeight: "160px",
  textAlign: "center",
  background: "#364d79",
};

const Restaurants = `query MyQuery {
  Restaurants {
    Category
    Description
    Image
    Name
    id
  }
}
`;

const Home = () => {


  const { data } = useQuery(Restaurants, {});
  console.log("data", data);

  useEffect(() => {
    try {
      localStorage.setItem("Cart", JSON.stringify([]));
    } catch (error) {
      console.log("error", error);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
     
        <Header >
          <Menu mode="horizontal" theme="dark" className={styles.header}>
            <Menu.Item key="sign_up"> <Link href={`/Sign-Up`}>Sign Up</Link></Menu.Item>

            <Menu.Item key="login">
              <Link href={`/Login`}>Login</Link>
            </Menu.Item>
            <Menu.Item key="contact">
              <a href="">Contact Us</a>
            </Menu.Item>
          </Menu>
        
        
        </Header>
        <Content>
          <Carousel autoplay>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={560} src={Img1} />
            </div>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={540} src={Img2} />
            </div>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={540} src={Img3} />
            </div>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={540} src={Img2} />
            </div>
          </Carousel>

          <Row className={styles.text}>
            <Col span={24}> Our Partners </Col>
          </Row>

          <Row justify="space-around">
            <Col span={24}>
              <Row gutter={[0, 15]}>
                {data &&
                  data.Restaurants.map((items) => {
                    return (
                      <>
                        <Col span={6}>
                          <Link href={`/Products?ct=${items.Category}`}>
                            <Card
                              style={{ width: 300, height: 300 }}
                              cover={
                                <img
                                  alt="example"
                                  src={`${items.Image}`}
                                  style={{ height: 200, width: 300 }}
                                />
                              }
                            >
                              <Meta
                                title={items.Name}
                                description={items.Description}
                              />
                            </Card>
                          </Link>
                        </Col>
                      </>
                    );
                  })}
              </Row>
            </Col>
          </Row>
        </Content>
        <Footer>
          .................................................
        </Footer>
      </Layout>
    </div>
  );
};

export default Home;
