import Head from "next/head";
import Image from "next/image";
import "antd/dist/antd.css"; // or 'antd/dist/antd.less'
import { Layout, Menu, Row, Col, Carousel,Typography } from "antd";
import styles from "../../styles/Home.module.css";
import { Card, Avatar } from "antd";
import { useQuery } from "graphql-hooks";
import Img1 from "../../public/Images/img-1.webp";
import Img2 from "../../public/Images/img-2.jpg";
import Img3 from "../../public/Images/img-3.jpg";
import Foodie from "../../public/Images/foodie-1.png";
import Foodie1 from "../../public/Images/foodie-2.jpg";
import Foodie2 from "../../public/Images/foodie-3.jpg";
import Link from "next/link";
import { useEffect,Fragment } from "react";
import  Dashboardheader  from "../Components/dashboardheader.js";
import  FooterComponent  from "../../pages/Components/footer.tsx";
import {CustomCol,CustomText} from ".././styled-components.tsx";
import {signIn, signOut, useSession} from "next-auth/react"
import { UserProvider } from "@auth0/nextjs-auth0";
const { Meta } = Card;
const { Header, Footer, Sider, Content } = Layout;
const contentStyle = {
  width: "100%",
  height: "auto",
  color: "#fff",
  lineHeight: "160px",
  textAlign: "center",
  background: "#364d79",
};

const Restaurants = `query MyQuery {
  Restaurants {
    Category
    Description
    Image
    Name
    id
  }
}
`;

const Home = () => {
  
  const { data } = useQuery(Restaurants, {});
  console.log("data", data);

  useEffect(() => {
    try {
      localStorage.setItem("Cart", JSON.stringify([]));
    } catch (error) {
      console.log("error", error);
    }
  }, []);
  const {Title} = Typography
  const { data: session } = useSession()
  return (
    <Fragment>
      <UserProvider>
    <div className={styles.container}>
      <Head>
        <title>Hey Foodie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboardheader/>
        <Content>
          <Carousel autoplay>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={560} src={Img1} />
            </div>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={540} src={Img3} />
            </div>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={540} src={Img1} />
            </div>
            <div style={contentStyle}>
              <Image preview={{ visible: false }} height={540} src={Img3} />
            </div>
          </Carousel>

          <Row className={styles.text}>
            <Col span={24}> Our Partners </Col>
          
          </Row>

          <Row>
            <Col span={24}>
              <Row justify="space-around" gutter={[0, 30]}>
                {data &&
                  data.Restaurants.map((items) => {
                    return (
                      <>
                        <Col span={5}>
                          <Link  href={`/Products?ct=${items.Category}`}>
                            <Card
                              style={{ width: 300, height: 300,cursor:"pointer"  }}
                              cover={
                                <img
                                  alt="example"
                                  src={`${items.Image}`}
                                  style={{ height: 200, width: 300 }}
                                />
                              }
                            >
                              <Meta
                                title={items.Name}
                                description={items.Description}
                              />
                            </Card>
                          </Link>
                        </Col>
                      </>
                    );
                  })}
              </Row>
            </Col>
          </Row>
          <Row style={{margin:"20px",backgroundColor:"#330608",padding:"50px"}}  justify="space-around">
            <Col span={7}> 
            <Row>
              <Col span={24} style={{justifyContent:"center",display:"flex"}}> <Image src={Foodie} height={200} width={200} /> </Col>
              <CustomCol span={24}>No Minimum Order </CustomCol>
              <CustomText span={24} > Order in for Yourself or for the group, with no restriction on order value.</CustomText>
            </Row>
            </Col>
            <Col span={7}>
            <Row>
              <Col span={24} style={{justifyContent:"center",display:"flex"}}> <Image  height={200} width={200} src={Foodie2}/>  </Col>
              <CustomCol span={24} > Live Order Tracking</CustomCol>
              <CustomText span={24}> Know Where Your Order is at all times from the restaurent to your doorstep.</CustomText>
            </Row>
            </Col>
            <Col span={7}>
            <Row>
              <Col span={24} style={{justifyContent:"center",display:"flex"}}> <Image  height={200} width={200} src={Foodie1}/>  </Col>
              <CustomCol span={24}>Lightning-Fast Delivery</CustomCol>
              <CustomText span={24}> Experince Foodie's Superfast delivery for food delivered fresh & on time..</CustomText>
            </Row>
            </Col>
          </Row>
        </Content>
        <Footer><FooterComponent/></Footer>
      </Layout>
    </div>
    </UserProvider>
    </Fragment>
  );
};

export default Home;
